package com.big9.app.ui.receipt


import android.os.Build
import android.os.Bundle
import android.view.KeyEvent
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.annotation.RequiresApi
import androidx.databinding.DataBindingUtil
import androidx.fragment.app.activityViewModels
import com.big9.app.R
import com.big9.app.data.viewMovel.MyViewModel
import com.big9.app.databinding.FragmentAgreementDialogBinding
import com.big9.app.ui.base.BaseCenterSheetFragment
import com.big9.app.utils.helpers.PermissionUtils
import com.big9.app.utils.`interface`.CallBack


class AgreementPageFragment(val callBack: CallBack) : BaseCenterSheetFragment() {
    lateinit var binding: FragmentAgreementDialogBinding
    private val viewModel: MyViewModel by activityViewModels()

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_agreement_dialog, container, false)
        binding.viewModel = viewModel
        binding.lifecycleOwner = this
        return binding.root
    }

    @RequiresApi(Build.VERSION_CODES.TIRAMISU)
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        initView()

        onViewClick()
    }

    @RequiresApi(Build.VERSION_CODES.TIRAMISU)
    private fun onViewClick() {
        binding.tvAgree.setOnClickListener{
            if (PermissionUtils.hasVideoRecordingPermissions(binding.tvAgree.context)){
                callBack.getValue("permission required")
                dismiss()
            }
            else{
             callBack.getValue("permission not required")
             dismiss()
            }

        }
        }


    fun initView() {
        setCrdViewMinHeight()

        /*val data = """
        Dear User,
        
        Thank you for choosing Big9. To provide you with the best experience and enable all of our app's features, we require the following permissions:
        
        • Bluetooth: This permission allows us to connect to Bluetooth devices for the Micro ATM Service. The Micro ATM (mATM) is a portable handheld device used for cash withdrawal from users' bank accounts. By granting this permission, you enable the app to communicate with the mATM device using Bluetooth for secure and convenient cash transactions.
        • Camera: We need access to your camera for the onboarding process. This allows us to capture images or videos necessary for verifying your identity and completing the setup of your account. Ensuring the security and accuracy of your information is our priority, and camera access helps us achieve this by enabling a seamless onboarding experience.
        • Record Audio: This permission is necessary for recording customer voice during the onboarding process. By capturing audio, we can securely verify your identity and authenticate your account setup through voice recognition. This enhances the security of your account while providing a convenient and efficient onboarding experience.
        • Access Media Location: This permission enables us to access media locations for capturing videos and images during the process of uploading them to our API. By having access to media locations, we can efficiently manage and organize the multimedia content generated by our application. This allows for seamless integration with our backend systems, enhancing the overall user experience.
        • Read External Storage: Required for accessing external storage to create and capture videos and images for uploading to our API. By having read access to external storage, our application can efficiently manage and utilize multimedia files stored on the device. This enables seamless integration with our API for uploading and sharing multimedia content, enhancing the overall user experience.
        • Write External Storage: Necessary for saving videos and images to the external storage of the device after they are created. This permission enables our application to store multimedia files locally, providing users with the ability to access and manage their captured media even when offline. Additionally, it allows for efficient storage management and facilitates the sharing of multimedia content across various applications on the device.
        • Access Fine Location: This permission is essential for accessing precise location information. It allows our application to obtain highly accurate location data, which is crucial for tasks such as connecting to Bluetooth devices with location-specific features and services. Additionally, it enables us to provide precise location-based features and services to enhance the user experience.

        • Access Coarse Location: Required for accessing approximate location information. This permission allows our application to obtain general location data, which is useful for tasks that do not require high precision, such as connecting to Bluetooth devices and obtaining user location during the login process. By having access to approximate location data, we can provide location-based functionalities while conserving battery and system resources.
        • Call Phone: This permission allows us to initiate phone calls programmatically for the purpose of automatically reading One-Time Passwords (OTPs) sent by Big9. By having access to this permission, our application can streamline the user authentication process by automatically detecting and reading OTPs from incoming messages, enhancing the overall user experience and security of the authentication process.
        
        Please be assured that we take your privacy and data security seriously. We only use these permissions to provide you with a seamless and secure experience within our app. Your data will never be shared with third parties without your consent.
        
        If you have any questions or concerns regarding these permissions, please feel free to contact us at [your contact information]. We appreciate your trust in us and hope you enjoy using [Your App Name].
        
        Sincerely,
        The Big9 Team
    """.trimIndent()*/

        val data = """
        Dear User,

        Thank you for choosing Big9. To provide you with the best experience and enable all of our app's features, we require the following permissions:
        
        Bluetooth: This permission allows us to connect to Bluetooth devices for the Micro ATM Service. The Micro ATM (mATM) is a portable handheld device used for cash withdrawal from users' bank accounts. By granting this permission, you enable the app to communicate with the mATM device using Bluetooth for secure and convenient cash transactions.
        
        Camera: We need access to your camera for the onboarding process. This allows us to capture images or videos necessary for verifying your identity and completing the setup of your account. Ensuring the security and accuracy of your information is our priority, and camera access helps us achieve this by enabling a seamless onboarding experience.
        
        Record Audio: This permission is necessary for recording customer voice during the onboarding process. By capturing audio, we can securely verify your identity and authenticate your account setup through voice recognition. This enhances the security of your account while providing a convenient and efficient onboarding experience.
        
        Access Media Location: This permission enables us to access media locations for capturing videos and images during the process of uploading them to our API. By having access to media locations, we can efficiently manage and organize the multimedia content generated by our application. This allows for seamless integration with our backend systems, enhancing the overall user experience.
        
        Read External Storage: Required for accessing external storage to create and capture videos and images for uploading to our API. By having read access to external storage, our application can efficiently manage and utilize multimedia files stored on the device. This enables seamless integration with our API for uploading and sharing multimedia content, enhancing the overall user experience.
        
        Write External Storage: Necessary for saving videos and images to the external storage of the device after they are created. This permission enables our application to store multimedia files locally, providing users with the ability to access and manage their captured media even when offline. Additionally, it allows for efficient storage management and facilitates the sharing of multimedia content across various applications on the device.
        
        Access Fine Location: This permission is essential for accessing precise location information. It allows our application to obtain highly accurate location data, which is crucial for tasks such as connecting to Bluetooth devices with location-specific features and services. Additionally, it enables us to provide precise location-based features and services to enhance the user experience.
        
        Access Coarse Location: Required for accessing approximate location information. This permission allows our application to obtain general location data, which is useful for tasks that do not require high precision, such as connecting to Bluetooth devices and obtaining user location during the login process. By having access to approximate location data, we can provide location-based functionalities while conserving battery and system resources.
        
        Call Phone: This permission allows us to initiate phone calls programmatically for the purpose of automatically reading One-Time Passwords (OTPs) sent by Big9. By having access to this permission, our application can streamline the user authentication process by automatically detecting and reading OTPs from incoming messages, enhancing the overall user experience and security of the authentication process.
        
        Please be assured that we take your privacy and data security seriously. We only use these permissions to provide you with a seamless and secure experience within our app. Your data will never be shared with third parties without your consent.
        
        If you have any questions or concerns regarding these permissions, please feel free to contact us at [your contact information]. We appreciate your trust in us and hope you enjoy using [Your App Name].
        
        Sincerely,
        The Big9 Team
    """.trimIndent()



        binding.tvMsg.text = data
    }

    private fun setCrdViewMinHeight() {
    }


    override fun onResume() {
        super.onResume()
        dialog?.setOnKeyListener { _, keyCode, _ ->
            if (keyCode == KeyEvent.KEYCODE_BACK) {
                // Handle back press event here
                // Return true to consume the back press and prevent the dialog from being dismissed
                false
            } else {
                // Return false to allow the default back press behavior (dismiss the dialog)
                false
            }
        }
    }

}